Discovery for HPE PDUs
Cray-HPE/hms-discovery pull request #25
Opened 2021-11-08 21:13 UTC by mbuchmann-hpe

### Summary and Scope

Update to discovery for HPE PDUs

### Issues and Related PRs

CASMHMS-5001

### Testing

Tested locally using the live PDU
Tested on Loki with HPE PDU
Tested on Shandy with ServerTech PDU

Were the install/upgrade based validation checks/tests run? N
Were continuous integration tests run? Y
Was an Upgrade tested? Y
Was a Downgrade tested? Y
If schema changes were part of this change, how were those handled in your upgrade/downgrade testing? NA

### Risks and Mitigations

Moderate risk - Changes should be limited to HPE redfish PDU

2021-11-22 16:33 UTC, mjendrysik-hpe commented on cmd/hms_discovery/river.go
> +	redfishURL := fmt.Sprintf("https://%s/redfish/v1", fqdn)
Will this break with other Redfish implementations? I was under the impression the trailing / was very important and some Redfish endpoints return an error when that trailing / is missing.

2021-11-22 21:05 UTC, mbuchmann-hpe commented on cmd/hms_discovery/river.go
> +	redfishURL := fmt.Sprintf("https://%s/redfish/v1", fqdn)
The other redfish devices support v1 without the trailing / or use a 301/302 to indicate the correct url to use and our go routines work with that.  I did change the code to check both without and with the trailing slash just incase there is a device that does not correctly support it.

2021-11-22 21:58 UTC, nieuwsma requested changes

2021-11-22 21:58 UTC, nieuwsma commented on cmd/hms_discovery/river_pdu.go
> +var pduUnknown = 0
Convert this to the go way to doing consts.  e.g. iotas.

2021-11-22 21:58 UTC, nieuwsma commented on cmd/hms_discovery/river_pdu.go
> +	} else {
Im not sure I understand the logic here. If the first request fails; just log it, but keep chugging along, assume it was probably an RTS pdu instead?

2021-11-22 21:58 UTC, nieuwsma commented on cmd/hms_discovery/river_pdu.go
> +	} else {
How do we not know PDU type solely by something in HSM?

2021-11-24 20:23 UTC, mbuchmann-hpe commented on cmd/hms_discovery/river_pdu.go
> +	} else {
First it checks the jawsURL for RTS PDUs (ServerTech)  if it receives a non 400 response, it marks the pdu type as RTS, then it checks the redfish/v1 URL - if it receives an ok, that makes it a redfish pdu.  Otherwise it fails as a unknown pdu type

2021-11-24 20:23 UTC, mbuchmann-hpe commented on cmd/hms_discovery/river_pdu.go
> +var pduUnknown = 0
Updated

2021-11-29 21:41 UTC, nieuwsma requested changes

2021-11-29 21:41 UTC, nieuwsma commented on cmd/hms_discovery/river.go
> +				if pduType == pduRedfish {
a pduType cannot be multiple types. Since you are using IOTA either use a switch statement; or use an else if.     IF unknown; CONTINUE; etc... make sense?

2021-11-29 21:41 UTC, nieuwsma commented on cmd/hms_discovery/river.go
>  			unknownComponent.CompID = xname
im confused about this being unknownComponent?   b/c dont we know the type? or what is ukknown?

2021-11-29 21:41 UTC, nieuwsma commented on cmd/hms_discovery/river.go
> +			err = fmt.Errorf("failed to execute GET request: %w", doErr)
what happens with these errs?

2021-11-29 21:41 UTC, nieuwsma commented on cmd/hms_discovery/river.go
> +	for _, redfishURL := range redfishURLs {
now that this is a for loop we are abandoning the errs...

2021-11-29 21:41 UTC, nieuwsma commented on cmd/hms_discovery/river_pdu.go
> +	} else {
Is this the only way to do it? we cannot do it based on something we know from HSM?
The downside to this approach is it doesnt take into consideration network failures, cred changes, etc.

2021-11-29 22:08 UTC, nieuwsma requested changes

2021-11-29 22:08 UTC, nieuwsma commented on cmd/hms_discovery/river.go
> +	for _, redfishURL := range redfishURLs {
if one of our two passes through succeeded then we are happy and dont care about the error; but if they both failed then we care about the failure.  So we need a sentinel value.  A boolean set to FALSE; if a full loop passes it gets set to true.   At the end if the sentinel is true we wipe the error and return; because we dont care about the error.

2021-11-29 22:08 UTC, nieuwsma commented on cmd/hms_discovery/river.go
>  			unknownComponent.CompID = xname
nvm its that we know the IP, the MAC but the not the Xname.  Ryan explained it to me.

2021-11-29 23:33 UTC, rsjostrand-hpe commented on cmd/hms_discovery/river.go
> +					continue
We want to break out of this loop: https://github.com/Cray-HPE/hms-discovery/blob/HPEPDU/cmd/hms_discovery/river.go#L180

We don’t need to continue looking at switch port mappings to identify this mac address as we already did. So we should give up on this MAC and move on to the next unknown component

2021-11-29 23:37 UTC, rsjostrand-hpe commented on cmd/hms_discovery/river.go
> +				if pduType == pduRedfish {
I think we should at least thing about using some if/if else/else here. We can also combine the `if pduType == pduRTS` statement that is farther below into it. Something like this should be good:
```go
if pduType == pduRedfish {
	// If Redfish PDU, continue below
	logger.Info("Found Redfish PDU", zap.String("xname", xname))
} else if pduType == pduRTS {
	// ServerTech PDUs are discovered differently then other types of hardware, as they do no talk native Redfish
	logger.Info("Found RTS PDU", zap.String("xname", xname))
	if informErr := informRTS(xname, xname, macWithoutPunctuation, unknownComponent); informErr != nil {
		logger.Error("Failed to notify RTS about PDU!",
			zap.Error(informErr),
			zap.String("xname", xname),
		)

		failedXnames = append(failedXnames, xname)
		break
	}

	logger.Info("Successfully identified and informed RTS about PDU.",
		zap.String("xname", xname),
		zap.String("managementSwitchXname", managementSwitchXname),
		zap.String("port", port),
	)

	globallyFound = true
	discoveredXnames = append(discoveredXnames, xname)

	break
} else {
	logger.Error("PDU Type Unknown", zap.String("xname", xname))
	break
}
```

2021-11-30 16:05 UTC, mbuchmann-hpe commented on cmd/hms_discovery/river.go
> +				if pduType == pduRedfish {
Updated to switch statement

2021-11-30 16:05 UTC, mbuchmann-hpe commented on cmd/hms_discovery/river.go
> +	for _, redfishURL := range redfishURLs {
Updated return statement

2021-11-30 16:06 UTC, mbuchmann-hpe commented on cmd/hms_discovery/river.go
> +					continue
Changed to break

2021-11-30 16:14 UTC, nieuwsma approved these changes

2021-11-30 16:36 UTC, rsjostrand-hpe approved these changes

2021-11-30 17:14 UTC, merged